window_duration: 1.7
sample_rate: 16000


n_fft: 480
win_length: 480
hop_length: 160
n_mels: 40

certainty_thresh: 0.7
certainty_detects: 3
certainty_window: 0

vad_release: 15

model_path: "weights/model_greeting100/model.pt"

db_host: "51.250.20.15"
db_port: 5432

sr_url: 'http://51.250.20.15:3030/asrupload'