window_duration: 1.7
sample_rate: 16000


n_fft: 480
win_length: 480
hop_length: 160
n_mels: 40

certainty_thresh: 0.7
certainty_detects: 3
certainty_window: 0

vad_release: 5

model_path: "weights/happy98/model.pt"

db_host: "localhost"
db_port: 5432

sr_url: 'http://127.0.0.1:8000/asrupload'