CREATE TABLE IF NOT EXISTS Badges(
  BadgeID TEXT PRIMARY KEY ,
  DateAdded TIMESTAMP,
  Activations INTEGER DEFAULT 0,
  Enabled BOOL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS Wakewords(
    ID INTEGER PRIMARY KEY ,
    WORD TEXT
);
CREATE TABLE IF NOT EXISTS Activations(
  BadgeID TEXT,
  DateTimeActivated TIMESTAMP,
  WakewordID INTEGER ,
  Duartion REAL DEFAULT 0,
  FOREIGN KEY(BadgeID) REFERENCES Badges(BadgeID),
  FOREIGN KEY(WakewordID) REFERENCES Wakewords(ID)
);